# Generated by Django 5.2.5 on 2025-08-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subject_is_complete_subject_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
