# Generated by Django 5.2.5 on 2025-08-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_audience', models.CharField(choices=[('ALL', 'All Users'), ('STUDENTS', 'All Students'), ('TEACHERS', 'All Teachers'), ('PARENTS', 'All Parents')], default='ALL', max_length=10)),
            ],
        ),
    ]
